name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23A78BFA&color_dots=%23EBEEF2%2C%23D8B4FE%2C%23C084FC%2C%23A855F7%2C%237C3AED
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2322D3EE&color_dots=%232D3343%2C%230F766E%2C%2310B981%2C%2334D399%2C%236D28D9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: dist
          GH_PAGES_BRANCH: output
